name: Deploy to AJ

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: andyjones81/github-actions/turnstyle@master
      name: Check workflow concurrency
      with:
        initial-wait-seconds: 15
        poll-interval-seconds: 15
        abort-after-seconds: 300
        same-branch-only: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: Build docs with middleman
      run: make build

